export type Feature = {
  title: string;
  summary: string;
  accent: string;
  detail: string;
};

export type CaseStudy = {
  slug: string;
  name: string;
  sector: string;
  result: string;
  detail: string;
  signals: string[];
  gaps: string[];
};

export const features: Feature[] = [
  {
    title: "Mixed page inventory",
    summary: "Landing, index, detail, and form pages give crawlers several shapes to inspect.",
    accent: "Route set",
    detail: "The first version keeps page content human-readable without adding search-specific metadata."
  },
  {
    title: "Baseline content density",
    summary: "Short sections, repeated cards, and plain labels create a neutral starting point for audits.",
    accent: "Copy mix",
    detail: "The copy is intentionally useful but not keyword tuned, so future SEO work has a clear before state."
  },
  {
    title: "Visual review surface",
    summary: "Grids, status strips, and detail panels provide stable screenshot targets for design checks.",
    accent: "UI states",
    detail: "The interface favors scannable product surfaces over SEO-specific content templates."
  }
];

export const caseStudies: CaseStudy[] = [
  {
    slug: "baseline-product-page",
    name: "Baseline Product Page",
    sector: "Commercial page",
    result: "Primary conversion copy without metadata support",
    detail: "A compact product-style page with headline copy, benefits, and proof points for future title, description, and structured data tests.",
    signals: ["Hero message", "Feature cards", "Plain internal links"],
    gaps: ["No canonical URL", "No Open Graph fields", "No product schema"]
  },
  {
    slug: "thin-article-page",
    name: "Thin Article Page",
    sector: "Editorial page",
    result: "Readable article shell with intentionally light depth",
    detail: "A lightweight article detail page that can be expanded later to compare thin content, internal linking, and heading improvements.",
    signals: ["Short body copy", "Related page link", "Single callout"],
    gaps: ["No author metadata", "No publish date metadata", "No article schema"]
  },
  {
    slug: "local-service-page",
    name: "Local Service Page",
    sector: "Location page",
    result: "Service area content without local SEO markup",
    detail: "A location-oriented page with service notes and contact prompts, useful for testing future local search enhancements.",
    signals: ["Service area copy", "Contact route link", "Operational details"],
    gaps: ["No local business schema", "No embedded map data", "No location-specific meta"]
  }
];

export const metrics = [
  { label: "Page types", value: "4" },
  { label: "SEO add-ons", value: "0" },
  { label: "Test records", value: "9" }
];

export const checkpoints = [
  "Scan raw page titles generated by the framework",
  "Compare how crawlers handle repeated card content",
  "Record missing metadata before optimization work",
  "Capture desktop and mobile screenshots for visual baselines"
];

export const baselineNotes = [
  {
    label: "Metadata",
    value: "Not configured"
  },
  {
    label: "Schema",
    value: "Not included"
  },
  {
    label: "Sitemap",
    value: "Not generated"
  },
  {
    label: "Robots",
    value: "Not customized"
  }
];
